name: Test Environment Setup

on:
  push:
    branches:
      - main

jobs:
  test-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Verify Java version
      run: java -version

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: '3.6.3'

    - name: Verify Maven version
      run: mvn -version
